@DientesLimpios.API_HostAddress = https://localhost:7272/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/01999B7B-F73B-7A18-AD31-55CC7EC6F1BD
Accept: application/json

###
GET {{DientesLimpios.API_HostAddress}}
Accept: application/json
Authorization: Bearer CfDJ8NsDbOLEWl5Hv5aOYRrZ1oeJykYPAFo5pJh1oSPlMWqrJxSgZ8Gj07WY73nf88wnup-re9Qdq-jVfWloSR_rR51Ly9MtS-iu9CA-OmMKTBtMX3JChTXErevf5XLyh3j8YG_Y_ozV2odw6Cto0Cq5uHtRVnHEMZ0UOjurfxuBt4JdzTnu-3oMwUCjf7cMQxaV7Np4M4FL7Z2cncTAMfhjqxnDqJJWVLiv2S2828BvNEq6maEy5ps_4kv1vvLRVOVls_gH1nKAsquo7-_XqoncZfZ5qwZMVU5lAgPL1tkZxK7r7pT1JFnjAtp4dgbJxIJmfQgn5A60lYVAyYf-bjL1P6YhoKQcLFFLG07k69jBTO4BmqRmy9M5Ei274LhxFj9A06dvIDYfgiG0f3p7xLmaPJ9CexgyDB0ULA_Ghe3Ldw80sy1qYHZHeLp5VVADgVPePseV2SdpEwAdO8lk0qgn-6jFWELbQNJsv4aCXGlBQeiqAokHrEdscFrvTHV2P6cD7tOmFSMz6HBu9q1OP6QGqFaIVjZ2JurI3tx4d3J9f6-KfM0DTRAIWwTeuwFDao0-A44bojU6lfw-cZjJbKQJ-Hi0Gy5A7lr_0gqpUCS-zFYr-TtNE29c-lcGHz0Z17BlXMJgq2UGRoWfoOeBmCv7WlZXB524DBfGA-uggrzwT5gVytan_nFb0i0mvHeKgKP_Dtz9-f6JzDNviN223jjn7C0HoMmYX5Ho0AO0KmhNRb7-

###
POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json
Authorization: Bearer CfDJ8NsDbOLEWl5Hv5aOYRrZ1oeJykYPAFo5pJh1oSPlMWqrJxSgZ8Gj07WY73nf88wnup-re9Qdq-jVfWloSR_rR51Ly9MtS-iu9CA-OmMKTBtMX3JChTXErevf5XLyh3j8YG_Y_ozV2odw6Cto0Cq5uHtRVnHEMZ0UOjurfxuBt4JdzTnu-3oMwUCjf7cMQxaV7Np4M4FL7Z2cncTAMfhjqxnDqJJWVLiv2S2828BvNEq6maEy5ps_4kv1vvLRVOVls_gH1nKAsquo7-_XqoncZfZ5qwZMVU5lAgPL1tkZxK7r7pT1JFnjAtp4dgbJxIJmfQgn5A60lYVAyYf-bjL1P6YhoKQcLFFLG07k69jBTO4BmqRmy9M5Ei274LhxFj9A06dvIDYfgiG0f3p7xLmaPJ9CexgyDB0ULA_Ghe3Ldw80sy1qYHZHeLp5VVADgVPePseV2SdpEwAdO8lk0qgn-6jFWELbQNJsv4aCXGlBQeiqAokHrEdscFrvTHV2P6cD7tOmFSMz6HBu9q1OP6QGqFaIVjZ2JurI3tx4d3J9f6-KfM0DTRAIWwTeuwFDao0-A44bojU6lfw-cZjJbKQJ-Hi0Gy5A7lr_0gqpUCS-zFYr-TtNE29c-lcGHz0Z17BlXMJgq2UGRoWfoOeBmCv7WlZXB524DBfGA-uggrzwT5gVytan_nFb0i0mvHeKgKP_Dtz9-f6JzDNviN223jjn7C0HoMmYX5Ho0AO0KmhNRb7-

{
  "nombre":"Consultorio C"
}

###
PUT {{DientesLimpios.API_HostAddress}}/0199d021-b74e-739f-9225-1a1cd7a59498
Content-Type: application/json
Authorization: Bearer CfDJ8NsDbOLEWl5Hv5aOYRrZ1oeJykYPAFo5pJh1oSPlMWqrJxSgZ8Gj07WY73nf88wnup-re9Qdq-jVfWloSR_rR51Ly9MtS-iu9CA-OmMKTBtMX3JChTXErevf5XLyh3j8YG_Y_ozV2odw6Cto0Cq5uHtRVnHEMZ0UOjurfxuBt4JdzTnu-3oMwUCjf7cMQxaV7Np4M4FL7Z2cncTAMfhjqxnDqJJWVLiv2S2828BvNEq6maEy5ps_4kv1vvLRVOVls_gH1nKAsquo7-_XqoncZfZ5qwZMVU5lAgPL1tkZxK7r7pT1JFnjAtp4dgbJxIJmfQgn5A60lYVAyYf-bjL1P6YhoKQcLFFLG07k69jBTO4BmqRmy9M5Ei274LhxFj9A06dvIDYfgiG0f3p7xLmaPJ9CexgyDB0ULA_Ghe3Ldw80sy1qYHZHeLp5VVADgVPePseV2SdpEwAdO8lk0qgn-6jFWELbQNJsv4aCXGlBQeiqAokHrEdscFrvTHV2P6cD7tOmFSMz6HBu9q1OP6QGqFaIVjZ2JurI3tx4d3J9f6-KfM0DTRAIWwTeuwFDao0-A44bojU6lfw-cZjJbKQJ-Hi0Gy5A7lr_0gqpUCS-zFYr-TtNE29c-lcGHz0Z17BlXMJgq2UGRoWfoOeBmCv7WlZXB524DBfGA-uggrzwT5gVytan_nFb0i0mvHeKgKP_Dtz9-f6JzDNviN223jjn7C0HoMmYX5Ho0AO0KmhNRb7-

{
  "nombre":"Consultorio C 2025"
}

###
DELETE {{DientesLimpios.API_HostAddress}}/01999b7b-f73b-7a18-ad31-55cc7ec6f1bc
Accept: application/json